#ifndef ROBOT_PINS_H
#define ROBOT_PINS_H

#include "driver/gpio.h"

#define MOTOR_IN1_PIN GPIO_NUM_14
#define MOTOR_IN2_PIN GPIO_NUM_27
#define MOTOR_IN3_PIN GPIO_NUM_26
#define MOTOR_IN4_PIN GPIO_NUM_25
#define MOTOR_ENA_PIN GPIO_NUM_33
#define MOTOR_ENB_PIN GPIO_NUM_32

#define SERVO_PIN GPIO_NUM_13
#define RELAY_PIN GPIO_NUM_23

#define FLAME_FRONT_PIN GPIO_NUM_34
#define FLAME_LEFT_PIN GPIO_NUM_35
#define FLAME_RIGHT_PIN GPIO_NUM_39

#define CAM_UART_TX_PIN GPIO_NUM_16
#define CAM_UART_RX_PIN GPIO_NUM_17

#define OLED_SDA_PIN GPIO_NUM_21
#define OLED_SCL_PIN GPIO_NUM_22

#endif
